nelmio_cors:
  defaults:
    allow_origin: ["http://localhost:3000"] # Autoriser Next.js
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/api/": # Chemin de l'API
      allow_origin: ["http://localhost:3000"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
      allow_headers: ["Content-Type", "Authorization"]
      max_age: 3600
